name: MAUI Android Build

on:
  push:
    branches: [ main ]

env:
  DOTNETVERSION: 6.0.400
  CONFIGURATION: Release
  FRAMEWORK: net6.0-android

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNETVERSION }}

    - run: |
        dotnet workload install maui

    - run: |
        dotnet restore

    - run: |
        dotnet publish -f ${{ env.FRAMEWORK }} -c ${{ env.CONFIGURATION }}

    - uses: actions/upload-artifact@v3
      with:
        path: |
          src/JinjuWeather/bin/${{ env.CONFIGURATION }}/${{ env.FRAMEWORK }}/publish/**/*.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3

    - uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: level120/CloudBandWagon-Android
        token: ${{ secrets.APP_CENTER }}
        group: Collaborators
        file: artifact/cloud.bandwagon.jinjuweather-Signed.apk