name: Build Hybrid App & Deploy App Center

on:
  push:
    branches: [ main ]

env:
  DotNetVersion: 6.0.405
  Configuration: Release
  Framework: net6.0-android
  AppId: cloud.bandwagon.jinjuweather

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - run: |
        dotnet workload install maui

    - run: |
        dotnet restore

    - run: |
        dotnet publish -f ${{ env.Framework }} -c ${{ env.Configuration }}

    - uses: actions/upload-artifact@v3
      with:
        path: |
          src/JinjuWeather/bin/${{ env.Configuration }}/${{ env.Framework }}/publish/**/*.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3

    - uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: level120/CloudBandWagon-Android
        token: ${{ secrets.APP_CENTER }}
        group: Collaborators
        file: artifact/${{ env.AppId }}-Signed.apk